baseURL = "/"

title = "Toolkit"
theme = ["fromago","sligo"]

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableInlineShortcodes = true
removePathAccents = true

[outputs]
  _merge = 'deep'
[cascade]
  _merge = 'deep'

[markup.goldmark.renderer]
    unsafe = true

[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    title = "Toolkit"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    title = "Toolkit"

